services:
  controller:
    build: ./controller
    networks:
      - neurolink-net
    ports:
      - "2340:2340"
    restart: unless-stopped
  neurolink:
    build: ./neurolink
    networks:
      - neurolink-net
    restart: unless-stopped
    expose:
      - "8080"

networks:
  neurolink-net:
    driver: bridge
